version: "3.9"

services:
  server:
#    build:
#      context: ./
#      dockerfile: server.dockerfile
    image: error1707/url_path_server
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  worker:
#    build:
#      context: ./
#      dockerfile: worker.dockerfile
    image: error1707/url_path_worker
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
