// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: protobuf/main.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SmallStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SomeString string `protobuf:"bytes,1,opt,name=SomeString,proto3" json:"SomeString,omitempty"`
	SomeInt    int32  `protobuf:"varint,2,opt,name=SomeInt,proto3" json:"SomeInt,omitempty"`
}

func (x *SmallStruct) Reset() {
	*x = SmallStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_main_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmallStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmallStruct) ProtoMessage() {}

func (x *SmallStruct) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_main_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmallStruct.ProtoReflect.Descriptor instead.
func (*SmallStruct) Descriptor() ([]byte, []int) {
	return file_protobuf_main_proto_rawDescGZIP(), []int{0}
}

func (x *SmallStruct) GetSomeString() string {
	if x != nil {
		return x.SomeString
	}
	return ""
}

func (x *SmallStruct) GetSomeInt() int32 {
	if x != nil {
		return x.SomeInt
	}
	return 0
}

type BigStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SomeText  string            `protobuf:"bytes,1,opt,name=SomeText,proto3" json:"SomeText,omitempty"`
	SomeInt   int32             `protobuf:"varint,2,opt,name=SomeInt,proto3" json:"SomeInt,omitempty"`
	SomeFloat float32           `protobuf:"fixed32,3,opt,name=SomeFloat,proto3" json:"SomeFloat,omitempty"`
	SomeMap   map[string]string `protobuf:"bytes,4,rep,name=SomeMap,proto3" json:"SomeMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SomeArray []*SmallStruct    `protobuf:"bytes,5,rep,name=SomeArray,proto3" json:"SomeArray,omitempty"`
}

func (x *BigStruct) Reset() {
	*x = BigStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_main_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BigStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigStruct) ProtoMessage() {}

func (x *BigStruct) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_main_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigStruct.ProtoReflect.Descriptor instead.
func (*BigStruct) Descriptor() ([]byte, []int) {
	return file_protobuf_main_proto_rawDescGZIP(), []int{1}
}

func (x *BigStruct) GetSomeText() string {
	if x != nil {
		return x.SomeText
	}
	return ""
}

func (x *BigStruct) GetSomeInt() int32 {
	if x != nil {
		return x.SomeInt
	}
	return 0
}

func (x *BigStruct) GetSomeFloat() float32 {
	if x != nil {
		return x.SomeFloat
	}
	return 0
}

func (x *BigStruct) GetSomeMap() map[string]string {
	if x != nil {
		return x.SomeMap
	}
	return nil
}

func (x *BigStruct) GetSomeArray() []*SmallStruct {
	if x != nil {
		return x.SomeArray
	}
	return nil
}

var File_protobuf_main_proto protoreflect.FileDescriptor

var file_protobuf_main_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x47, 0x0a, 0x0b, 0x53,
	0x6d, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x6f,
	0x6d, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x53, 0x6f, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x6f,
	0x6d, 0x65, 0x49, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x53, 0x6f, 0x6d,
	0x65, 0x49, 0x6e, 0x74, 0x22, 0x84, 0x02, 0x0a, 0x09, 0x42, 0x69, 0x67, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x6f, 0x6d, 0x65, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x6f, 0x6d, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x53, 0x6f, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x53, 0x6f, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f, 0x6d, 0x65,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x53, 0x6f, 0x6d,
	0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x53, 0x6f, 0x6d, 0x65, 0x4d, 0x61,
	0x70, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x42,
	0x69, 0x67, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x53, 0x6f, 0x6d, 0x65, 0x4d, 0x61, 0x70,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x53, 0x6f, 0x6d, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x2f,
	0x0a, 0x09, 0x53, 0x6f, 0x6d, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x52, 0x09, 0x53, 0x6f, 0x6d, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x1a,
	0x3a, 0x0a, 0x0c, 0x53, 0x6f, 0x6d, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_main_proto_rawDescOnce sync.Once
	file_protobuf_main_proto_rawDescData = file_protobuf_main_proto_rawDesc
)

func file_protobuf_main_proto_rawDescGZIP() []byte {
	file_protobuf_main_proto_rawDescOnce.Do(func() {
		file_protobuf_main_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_main_proto_rawDescData)
	})
	return file_protobuf_main_proto_rawDescData
}

var file_protobuf_main_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_main_proto_goTypes = []interface{}{
	(*SmallStruct)(nil), // 0: main.SmallStruct
	(*BigStruct)(nil),   // 1: main.BigStruct
	nil,                 // 2: main.BigStruct.SomeMapEntry
}
var file_protobuf_main_proto_depIdxs = []int32{
	2, // 0: main.BigStruct.SomeMap:type_name -> main.BigStruct.SomeMapEntry
	0, // 1: main.BigStruct.SomeArray:type_name -> main.SmallStruct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_main_proto_init() }
func file_protobuf_main_proto_init() {
	if File_protobuf_main_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_main_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmallStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_main_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BigStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_main_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_main_proto_goTypes,
		DependencyIndexes: file_protobuf_main_proto_depIdxs,
		MessageInfos:      file_protobuf_main_proto_msgTypes,
	}.Build()
	File_protobuf_main_proto = out.File
	file_protobuf_main_proto_rawDesc = nil
	file_protobuf_main_proto_goTypes = nil
	file_protobuf_main_proto_depIdxs = nil
}
